### ISSUE TITLE
2019-06-13 meeting notes

### ISSUE THREAD

**Issue by mayhemer** [mozilla-necko/meeting-notes#27] opened 2019-06-12 14:49 UTC
**Round table:**
bug 1556347

**Next on triage duty:**
Michal

**Comment by mayhemer** [comment] 2019-06-13 16:32
[1463729 - Fast h2 rx may block the socket thread from processing messages](https://bugzilla.mozilla.org/show_bug.cgi?id=1463729)

**Comment by ddragana** [comment] 2019-06-13 16:32
Necko-neqo integration.
Honza's log

**Comment by agrover** [comment] 2019-06-13 16:34
QUIC/Neqo
* PR merged: Converted to Instant/Duration from u64 nanos
  * spawned 7 new issues :frowning: 
* pre-review: Refactored timer code
* pre-review: neqo-h3-server: support for timers in event loop
* pre-review: Fix a connection close bug
* next: Review mt's massive 0-RTT PR
* next: Read Dragana's doc

DoH/TRR Mitigation
* Global Canary

**Comment by JuniorHsu** [comment] 2019-06-13 16:34
Bug 1504085 - Origin header honors ReferrerPolicy: r+, fixing treeherder
fetch spec: Fix referrer-policy setup for fetch
Bug 1513865 - [socket-process] nsIPrefService.resetPrefs does not work - finding out why IOService can't recognize pref change in js test

**Comment by vonasek** [comment] 2019-06-13 16:36
- 1547266 - secure bug
- 1528481 - secure bug
- 1478950 - Fix parsing filename in OS/2 FTP listing
- 1557893 - Diskcache size in about:cache does not fit to about:preferences and even not to real size on disk

**Comment by valenting** [comment] 2019-06-13 16:38
### landed

Bug [1459573](https://bugzil.la/1459573) - Support Cross Origin Resource Policy (CORP)

### working on
Bug [1527314](https://bugzil.la/1527314) - Expand Cross-Origin-Opener-Policy tests
 - Intermittent timeouts in verify runs.
 - Logging makes it not reproduce. Reason unclear.

Bug [1551601](https://bugzil.la/1551601) - Perform cross-process switch before processing cached redirect
 - Caused by several bugs:
    - After process switch the loadInfo points to the wrong browsingContext
    - Call to wg.changeFrameRemoteness in SessionStore.jsm fails because GetEmbedderElement returns null
    - BrowserParent::RecvFireFrameLoadEvent is called after the actor is destroyed.

Bug [1395914](https://bugzil.la/1395914) - Figure out network id for IPv6 too
Bug [1555036](https://bugzil.la/1555036) - COOP: check browsing context's popup sandboxing flag
Bug [1558495](https://bugzil.la/1558495) - force retry after a TRR server was down intermittently (in mode 3 only)
Bug [1558858](https://bugzil.la/1558858) - Add XPCOM API for inspecting DNS requests/responses
  - needed for TRR experiment 7

**Comment by nhi-nguyen** [comment] 2019-06-13 16:39
* performance review
* contractor interviewing
* all-hands

**Closed** 2019-06-26 18:03 UTC
