### ISSUE TITLE
2020-04-16 meeting notes

### ISSUE THREAD

**Issue by KershawChang** [mozilla-necko/meeting-notes#68] opened 2020-04-16 14:50 UTC
**Round table:**
- Moving proxy resolution to socket process. Can we detect proxy configuration changes?
- [unassigned P1](https://mzl.la/2Ke9Coc)
- [PAC scripts over FTP](https://bugzilla.mozilla.org/show_bug.cgi?id=1622335)

**Next on triage duty:**
Honza.

**Comment by agrover** [comment] 2020-04-16 16:29
Triage

Neqo
* H3 disabled in Nightly due to Google* issues
* New Neqo Eng Weekly meeting
* interop container image issues
* qlog PR good to land (once reviewer comments addressed)
* Neqo breakage due to NSS changes
* Simplifying API work: eliminating process_http3(); eliminating process_timer()

DoH
* Canary: Telemetry shows canary abuse by CenturyLink. First response is to reach out and ask what's up.
* UI: We have a UI person, initial meeting with them on Tuesday

Next:
* Get more organized for more people on Neqo, more mgmt scrutiny
* Land qlog
* Resolve API issues
* More interop/testing work

**Comment by valenting** [comment] 2020-04-16 16:29
Bug [1595886](https://bugzil.la/1595886) - [done]
Bug [1625749](https://bugzil.la/1625749) - [done]
Bug [1625563](https://bugzil.la/1625563) - Intermittent test_trr.js::test_resolve_not_confirmed [landed]
Bug [1619673](https://bugzil.la/1619673) - Disable appcache in release [landed]
Bug [1623126](https://bugzil.la/1623126) - Implement HTTPSSVC
Bug [1595848](https://bugzil.la/1595848) - Intermittent COOP/COEP tests

**Comment by ddragana** [comment] 2020-04-16 16:30
need-infos and reviews
neqo: 
Issue [547](https://github.com/mozilla/neqo/pull/547) - Turn on clippy pedantics for neqo-http3
Issue [544](https://github.com/mozilla/neqo/pull/544)  - Set the idle timeout to 30s
Issue [538](https://github.com/mozilla/neqo/pull/538) - Check if transaction is done(), do not check only fin before removing a transaction
Issue [537](https://github.com/mozilla/neqo/pull/537) - Fix debug assertion in encode_headr_block

**Comment by KershawChang** [comment] 2020-04-16 16:31
Landed/Complete:
- `rel=preload` review

Ongoing:
- [Bug 1497249](https://bugzilla.mozilla.org/show_bug.cgi?id=1497249) - [socket-proc] Connection stickiness handling for upgrade observers
- [Bug 1626076](https://bugzilla.mozilla.org/show_bug.cgi?id=1626076) - Use DataStorage on socket process
 - [Bug 1539819](https://bugzilla.mozilla.org/show_bug.cgi?id=1539819) - [socket process] TRR is not working in socket process
- [Bug 1485652](https://bugzilla.mozilla.org/show_bug.cgi?id=1485652) - Make nsNSSSocketInfo::IsAcceptableForHost work asynchronously on the socket process

**Comment by JuniorHsu** [comment] 2020-04-16 16:32
Bug 1554218 - Handle 407 from a HTTP/2 proxy
OnStart/StopRequest OMT: image (good to OMT but not trivial), CSS (no)

**Comment by vonasek** [comment] 2020-04-16 16:32
- 1622335 Add telemetry for PAC scripts served over FTP
- Effect of cache partitioning
- Quic network-simulator

**Comment by mayhemer** [comment] 2020-04-16 17:01
* preload
  * all M1 bugs but one patch r+
  * pushing to try
  * perf testing request when green (enough)
  * some bugs for M2 on the way (fetch, font: r?)
* Bug 1605895

**Closed** 2020-04-22 17:33 UTC
