### ISSUE TITLE
2020-06-25 meeting notes

### ISSUE THREAD

**Issue by agrover** [mozilla-necko/meeting-notes#77] opened 2020-06-11 16:25 UTC
**Round table:**
* are VPN related bugs ([1638542](https://bugzil.la/1638542), [1647985](https://bugzil.la/1647985), [1635935](https://bugzil.la/1635935)) higher priority now when DoH is also affected?

**Next on triage duty:** Valentin

**Comment by agrover** [comment] 2020-06-11 16:25
dup

**Comment by mayhemer** [comment] 2020-06-25 15:02
READONLY (can't attend for personal reasons)
* [1648471 - [rel=preload] Enable <link rel=preload> fully on Beta 79](https://bugzilla.mozilla.org/show_bug.cgi?id=1648471) we don't have a macro for that 
* landed [1631327 - Crash in \[@ IPCError-browser | RecvPredLearn\]](https://bugzilla.mozilla.org/show_bug.cgi?id=1631327)
* landed [1487101 - CacheStorageService::PurgeOverMemoryLimit() doesn't work correctly under specific circumstances](https://bugzilla.mozilla.org/show_bug.cgi?id=1487101)
* landed [1603542 - \[rel=preload\] Log a warning when preloaded resources are not used](https://bugzilla.mozilla.org/show_bug.cgi?id=1603542)
* landed [1638925 - Extend events MOZ\_LOG module](https://bugzilla.mozilla.org/show_bug.cgi?id=1638925), includes IPC, DOM promises, message queue, logan updated too, I will intro some other time
* moved on a bit with 1605895
* reduced my ni? queue greatly!
* next [1639914 - SEC_ERROR_OCSP_SERVER_ERROR with most https websites when security.OCSP.require is set to true and a https .pac file is used](https://bugzilla.mozilla.org/show_bug.cgi?id=1639914)
* next [1632215 - Intermittent SUMMARY: ThreadSanitizer: data race /builds/worker/checkouts/gecko/netwerk/protocol/http/nsHttpChannel.cpp:8439:7 in mozilla::net::nsHttpChannel::OnDataAvailable(nsIRequest*, nsIInputStream*, unsigned long, unsigned int)](https://bugzilla.mozilla.org/show_bug.cgi?id=1632215)
* next [1560090 - High refresh rate monitor (>200Hz) slows performance](https://bugzilla.mozilla.org/show_bug.cgi?id=1560090)

**Comment by vonasek** [comment] 2020-06-25 15:04
readonly

- triage
- 1643866 Firefox fails to resolve specific domain: NS_ERROR_UNKNOWN_HOST
- 1645797 PR_CONNECT_RESET_ERROR when connecting to belastingdienst.nl
- 1644374 Assertion *countWritten > 0 in nsHttpTransaction::WritePipeSegment
- PR750 neqo-qns
- PR755 QNS qlog
- PR768 neqo-client: fix QNS compliance check
- PR765 - fix zerortt QNS test
- 1627910 Enable test netwerk/test/unit/test_http3

**Comment by KershawChang** [comment] 2020-06-25 16:19
Landed:
- [Bug 1644239](https://bugzilla.mozilla.org/show_bug.cgi?id=1644239) - Crash in [@ mozilla::net::Http2Session::RecvPushPromise]
- [Bug 1644834](https://bugzilla.mozilla.org/show_bug.cgi?id=1644834) - about:memory tests fail on my machines (macOS Catalina, Ubuntu 18.04)
- [Bug 1643515](https://bugzilla.mozilla.org/show_bug.cgi?id=1643515) - Crash in [@ mozilla::net::HttpTransactionParent::DoNotifyListener]
- [Bug 1640612](https://bugzilla.mozilla.org/show_bug.cgi?id=1640612) - socket process gets killed due to sandboxing

Ongoing:
- triage
- [Bug 1646358](https://bugzilla.mozilla.org/show_bug.cgi?id=1646358) - [socket process] Fix test failures regarding devtool tests
- [Bug 1647096](https://bugzilla.mozilla.org/show_bug.cgi?id=1647096) - GeckoProfiler.Markers gtest crashes after changing tests to use socket process
- [Bug 1646689](https://bugzilla.mozilla.org/show_bug.cgi?id=1646689) - 2.01 - 4.86% raptor-tp6m-allrecipes-geckoview-cold loadtime / raptor-tp6m-cnn-geckoview-cold confidence (android-hw-g5-7-0-arm7-api-16-shippable) regression on push 567513cee4895872b1e7fb53fbd2793593d11f97 (Fri June 5 2020)
- [Bug 1648189](https://bugzilla.mozilla.org/show_bug.cgi?id=1648189) - [socket process] Perma Assertion failure: tqParent, at /builds/worker/checkouts/gecko/netwerk/protocol/http/HttpTransactionParent.cpp:173

**Comment by undef1nd** [comment] 2020-06-25 16:28
Implemented headers serializer
Added specification tests from https://github.com/httpwg/structured-field-tests 

Working on XPIDL bindings for structured-headers crate

**Comment by JuniorHsu** [comment] 2020-06-25 16:28
- Landed
    - [Bug 1633935 - Allow sending onStartRequest via pHttpBackgroundChannel](https://bugzilla.mozilla.org/show_bug.cgi?id=1633935)
        - Depends on
            - [Bug 1645941 - data race StreamFilterParent::mState in OnStartRequest and ODA](https://bugzilla.mozilla.org/show_bug.cgi?id=1645941)
            - [Bug 1645527 - Remove redundant PHttpChannel IPCs](https://bugzilla.mozilla.org/show_bug.cgi?id=1645527)
        - Regressions
            - [Bug 1648132 - Crash in [@ mozilla::extensions::StreamFilterParent::Init]](https://bugzilla.mozilla.org/show_bug.cgi?id=1648132)
- Next
    - [Bug 1645901 - Send necessary cookie through pBackground before OnStartRequest](https://bugzilla.mozilla.org/show_bug.cgi?id=1645901)
    - [Bug 1646592 - Sending endpoint of stream filter should not block main thread IPC](https://bugzilla.mozilla.org/show_bug.cgi?id=1646592)
    - [Bug 1648035 - Intermittent Assertion failure: mChannelChild (no channel child in RecvOnStatus), at /builds/worker/checkouts/gecko/netwerk/protocol/http/HttpBackgroundChannelChild.cpp:160](https://bugzilla.mozilla.org/show_bug.cgi?id=1648035)
    - [Bug 1578230 - Crash [@ mozilla::net::SpdyConnectTransaction::MapStreamToHttpConnection] with HTTP2 Proxy](https://bugzilla.mozilla.org/show_bug.cgi?id=1578230)

**Comment by valenting** [comment] 2020-06-25 16:31
Bug 1647638   Add nsStandardURL assertions
Bug 1618271 - DNS leaks about `browser.dns` API

TRR documentation
rust-url fixes
DNS code refactoring

**Comment by agrover** [comment] 2020-06-25 16:33
[Neqo (6,49,57)](https://github.com/mozilla/neqo/projects/2)(-2,+3,+1):
* Neqo 0.4.4 tagged and merged into m-c.
* PR 754 Properly handle receipt of StreamDataBlocked frame
* PR 746 Avoid borrowing FlowMgr twice when handling lost MaxStreamData token 
* [in-review] PR 752 Implement more qlog traces: CC and Recovery state
* WIP: Add network.http.http3.qlog_dir pref to Firefox. Works, but needs as-yet-untagged Neqo changes before can be posted for review
* WIP: Set Qlog dir via about:networking (depends on above)
* PR Reviews
* Tried to get QNS Docker image autobuilding from GitHub commit without success. Some sort of permissions issue? Maybe moving neqo repo to mozilla-necko org would make easier.

Next:
* Fix Neqo issues
* Confirm DoH canary abuse and take follow-up actions

**Comment by ddragana** [comment] 2020-06-25 16:50
Doc about HTTP3 Performance study
Requirements for turning Http3 in Nightly (a doc)
Looking on Http3 bugs in Firefox
Add support for draft28 and draft29 in m.-c.
PR [766](https://github.com/mozilla/neqo/pull/766) - Write the header block's prefix properly
Bug 1646318 - test_post and test_patch in netwerk/test/unit/test_http3.js time out

**Closed** 2020-07-09 15:51 UTC
