### ISSUE TITLE
2020-05-28 meeting notes

### ISSUE THREAD

**Issue by mayhemer** [mozilla-necko/meeting-notes#74] opened 2020-05-28 14:37 UTC
**Round table:**

**Next on triage duty:**
Dragana

**Comment by mayhemer** [comment] 2020-05-28 14:56
preload:
* enabled by default on Nightly (and rides to Early Beta only)
* investigating a perf regressions: [1641532 - 2.9 - 17.82% raptor-tp6- (linux64, macosx1014-64-shippable, windows10) regression on push 2bccc3e80006f2ad27060453135b19fac2d43460 (Tue May 26 2020)](https://bugzilla.mozilla.org/show_bug.cgi?id=1641532)

**Comment by valenting** [comment] 2020-05-28 16:25
[landed]
Bug [1611990](https://bugzil.la/1611990) - Rust log messages of less than WARN level are optimized out [#645](https://github.com/mozilla/neqo/pull/645)
Bug [1635566](https://bugzil.la/1635566) - logincdn.msauth.net fails to resolve if network.trr.mode=3
Bug [1636891](https://bugzil.la/1636891) - Move logging specifics from toolkit/library/rust/shared/lib.rs to the gecko_logger crate
Bug [1640872](https://bugzil.la/1640872) - Add more TRR logging
Bug [1640879](https://bugzil.la/1640879) - Fix COEP data.http.html test

[working on]
Bug [1641222](https://bugzil.la/1641222) - Follow CNAME/AliasForm chains
Bug [1616252](https://bugzil.la/1616252) - Maybe add a /etc/hosts parser
Bug [1636888](https://bugzil.la/1636888) - Allow specifying entire rust modules in MOZ_LOG
Bug [1627800](https://bugzil.la/1627800) - 404 http error isn't displayed in Firefox
Bug [1629862](https://bugzil.la/1629862) - Improve error messages for COEP failures

**Comment by ddragana** [comment] 2020-05-28 16:27
Working on improving neqo-http3 code and implementing ServerPush:
- Done: PR [657](https://github.com/mozilla/neqo/pull/657) - Use separate send_message/recv_message instead of transactions
- One more small refactor and ServerPush PRs almost ready

Working on HTTP3/QUIC telemetry doc
PR [669](https://github.com/mozilla/neqo/pull/669) - Drop packets with unknown versions

neqo reviews

Open some Http3 spec issues

**Comment by vonasek** [comment] 2020-05-28 16:28
- [landed] 1637947 network ID: link status isn't updated in NetlinkService::OnAddrMessage()
- [landed] Neqo PR667 - Add test chacha20
- [landed] Neqo PR663 - Add retry, resumption and zerortt tests
- Issue 674 - Handle Error::StreamLimitError returned from Connection::stream_create
- Issue 676 - neqo-server: implement "transfer" test case
- 1621345 Support for nsIWebSocketEventListener.send() API
- FTP PAC telemetry data from release

**Comment by undef1nd** [comment] 2020-05-28 16:29
Continue working on structured http headers parser

**Comment by KershawChang** [comment] 2020-05-28 16:29
Landed:
- [Bug 1629457](https://bugzilla.mozilla.org/show_bug.cgi?id=1629457) - Intermittent netwerk/test/unit/test_trr.js | application crashed [@ __thiscall InitHash::InitHash + 0x12d3] | TRRServiceChannel using nsWeakReference OffMainThread
- [Bug 1546358](https://bugzilla.mozilla.org/show_bug.cgi?id=1546358) - [socket process] cache storage service is used in Http2Session
- [Bug 1602832](https://bugzilla.mozilla.org/show_bug.cgi?id=1602832) - [socket process] Enable xpcshell tests for socket process
- [Bug 1641427](https://bugzilla.mozilla.org/show_bug.cgi?id=1641427) - startup Crash in [@ mozilla::SandboxBroker::LaunchApp]

Ongoing:
- [Bug 1637648](https://bugzilla.mozilla.org/show_bug.cgi?id=1637648) - [socket process] Forward observer notifications in nsHttpHandler to socket process
- [Bug 1641496](https://bugzilla.mozilla.org/show_bug.cgi?id=1641496) - [socket process] Investigate disabled xpcshell tests
- [Bug 1640612](https://bugzilla.mozilla.org/show_bug.cgi?id=1640612) - socket process gets killed due to sandboxing
- [Bug 1640105](https://bugzilla.mozilla.org/show_bug.cgi?id=1640105) - [socket process] Run mochitest with networking over socket process enabled
- [Bug 1524035](https://bugzilla.mozilla.org/show_bug.cgi?id=1524035) - Assertions in socket process do not output a stack trace
- [Bug 1638387](https://bugzilla.mozilla.org/show_bug.cgi?id=1638387) - nsOSXSystemProxySettings::Init() is failed in socket process when sandbox is enabled

**Comment by JuniorHsu** [comment] 2020-05-28 16:32
Bug 1633935 - Allow sending onStartRequest via pHttpBackgroundChannel
- all r+, fixing regression - cross-process redirection/onStart before permission received/graphic async test/...
[landed] Bug 1638172 - avoid name hiding for handling multipart channel in HttpChannelChild
[landed] Bug 1638313 - Cross-Origin request blocked is not visible in Network panel

**Closed** 2020-06-05 22:03 UTC
