### ISSUE TITLE
2020-02-27 meeting notes

### ISSUE THREAD

**Issue by mayhemer** [mozilla-necko/meeting-notes#61] opened 2020-02-27 16:23 UTC
**Round table:**

**Next on triage duty:**
Honza - being OK with it

**Comment by mayhemer** [comment] 2020-02-27 16:26
* [Preload project planning](https://docs.google.com/document/d/11iAbml3EOyE8jxsB0-NLfxLWoDzIq-jCKJHAwLnM7z0/edit?usp=sharing) (being approved) 
* Investigating [1616082 - Crash in [@ shutdownhang | nsThread::Shutdown | mozilla::net::WaitForThreadShutdown::Run | nsThread::Shutdown | ProfileResetCleanupResultTask::Run]](https://bugzilla.mozilla.org/show_bug.cgi?id=1616082)
* reviews
* ni?
* having issues with my main desktop dev machine at the time :/ (lost all emails!)

**Comment by valenting** [comment] 2020-02-27 17:02
Read-only (PTO)

Bug [1617889](https://bugzil.la/1617889) - Fix COOP comparison
Bug [1595848](https://bugzil.la/1595848) - Intermittent COOP/COEP tests
Bug [1618130](https://bugzil.la/1618130) - Add API to override platform DNS results
Bug [1605775](https://bugzil.la/1605775) - ESNI: Repeated DNS lookups over DoH
Bug [1611651](https://bugzil.la/1611651) - TRR: Infinite loop when visiting https://1.1.1.1/help
  - isolated a test case
  - caused by stale-while-revalidate -> Honza

Shout-out to Kershaw for finding and fixing TRR performance bug
Bug [1618173](https://bugzil.la/1618173) - TRR: We don't use DNS cache at all for the URL of DoH server

**Comment by vonasek** [comment] 2020-02-27 17:12
- [landed] 1617036 Remove NETWORK_TIME_BETWEEN_NETWORK_CHANGE_EVENTS probe 
- [landed] 1614610 Have cache occupancy for each content-type in cache index
- [landed] 1616507 Data race /builds/worker/workspace/build/src/netwerk/cache2/CacheFile.cpp:2362:48 in EntryWouldExceedLimit
- 1614619 Eviction algorithm should first evict entries of a content type that's above a limit
- 1615017 ThreadSanitizer: data race [@ mozilla::net::CacheFileMetadata::SetHash] vs. [@ MemoryUsage]
- 1615533 Can not establish websocket connections with socks proxy
- 1424820 "Use system proxy settings" uses SOCKSv4
- 1601671 websocket connects to DIRECT instead of Proxy-HTTP/HTTPS with SystemProxySettings in Windows
- 1587353 Add tests for http3

**Comment by KershawChang** [comment] 2020-02-27 17:19
Landed:
- [Bug 1616549](https://bugzilla.mozilla.org/show_bug.cgi?id=1616549) - toolkit/components/antitracking/test/browser/browser_networkIsolation.js failed with SSLTokensCache enabled
- [Bug 1618173](https://bugzilla.mozilla.org/show_bug.cgi?id=1618173) - TRR: We don't use DNS cache at all for the URL of DoH server
- [Bug 1607134](https://bugzilla.mozilla.org/show_bug.cgi?id=1607134) - ThreadSanitizer: data race [@ mozilla::net::ProxyAutoConfig::SetThreadLocalIndex] vs. [@ GetRunning] on mozilla::net::sRunningIndex
- [Bug 1607445](https://bugzilla.mozilla.org/show_bug.cgi?id=1607445) - Make it possible to clear session cache stored in SSLTokensCache

Ongoing:
- Security review for SimpleHttpChannel
- [Bug 1613873](https://bugzilla.mozilla.org/show_bug.cgi?id=1613873) - Create a simple http channel which is only used for TRR
- [Bug 1615335](https://bugzilla.mozilla.org/show_bug.cgi?id=1615335) - TRR: Use SimpleHttpChannel off main thread
- [Bug 1584104](https://bugzilla.mozilla.org/show_bug.cgi?id=1584104) - We need to have a clone of TransportSecurityInfo on the parent process
-  [Bug 1527384](https://bugzilla.mozilla.org/show_bug.cgi?id=1527384) - [socket process] Make SpeculativeConnect work

**Comment by agrover** [comment] 2020-02-27 17:35
Neqo:
* QLOG support PR posted for review
* Review of other PRs
* Support for quic-network-interop
  * Docker image
  * changes needed to neqo-client

doh canary
  * Write-up on disabling canary for ISPs that abuse it

**Comment by ddragana** [comment] 2020-02-27 17:40
Bug 1582663 - Maybe we should split nsHttpConnection - ready to land
Working on:
- QPack refactor
- testing Http3 in Firefox and fixing some bugs (I need to file bug yet)

**Closed** 2020-03-11 16:47 UTC
